name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # AJOUT IMPORTANT : On définit le dossier de travail par défaut pour toutes les commandes "run"
    defaults:
      run:
        working-directory: ./bank-application

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          # On précise le chemin du pom.xml pour le cache
          cache-dependency-path: bank-application/pom.xml

      # 3. Lancer les tests (S'exécute maintenant DANS bank-application)
      - name: Run Tests
        run: mvn clean test

      # 4. Faire le package
      - name: Package Application
        run: mvn package -DskipTests

      # 5. Sauvegarder l'artefact
      # Attention : Le chemin "target/" change aussi, il faut préciser le sous-dossier ici
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bank-app-target-folder
          path: bank-application/target/
          retention-days: 1